app_port: 6000
#grpc_port: 50000
debug: false

# use app show tags
# eg: cron,api,metrics
#exclude_server: ""

# 'logrus' | 'zap'
#log_channel: "logrus"

# 开启 git 请求缓存，默认开启，因为 git 请求比较慢，需要缓存
git_server_cached: true

# db_auto_migrate 默认是 false
# v4->v5 因为表结构发生改动(不兼容)，所以需要设置为 false, 防止自动迁移数据库表结构
db_auto_migrate: false

# 'db' or 'memory'
cache_driver: "memory"

git_server_plugin:
  name: gitlab
  args:
    token: ""
    baseurl: "https://gitlab.com/api/v4"
ws_sender_plugin:
  name: ws_sender_memory
#  name: ws_sender_nsq
#  args:
#    addr: 127.0.0.1:4150
#    lookupd_addr 可选，有就用
#    lookupd_addr: 127.0.0.1:4160
#  name: ws_sender_redis
#  args:
#    addr: 127.0.0.1:6379
#    password: ""
#    db: 1
domain_manager_plugin:
  name: default_domain_manager
#  name: manual_domain_manager
#  args:
#    wildcard_domain: "*.mars.local"
#    tls_key: ""
#    tls_crt: ""
#  name: sync_secret_domain_manager
#  args:
#    wildcard_domain: "*.mars.local"
#    secret_name: ""
#    secret_namespace: ""
#  name: cert-manager_domain_manager
#  args:
#    wildcard_domain: "*.mars.local"
#    cluster_issuer: "letsencrypt-mars"
picture_plugin:
  name: picture_bing
#  name: picture_cartoon

# kubeconfig 如果在集群外部，则需要配置，否则不用
kubeconfig: ""

# upload_dir 默认是 /tmp/mars-uploads
#upload_dir: ""

# 默认 50m, 使用 MB,Gi,m,g这样的写法
#upload_max_size: "50m"

# 文件上传到 s3
s3_enabled: false
s3_endpoint: ""
s3_access_key_id: ""
s3_secret_access_key: ""
s3_use_ssl: false
s3_bucket: mars

# database
# 'sqlite' or 'mysql', 如果是 'sqlite', 'db_database' 为 db 绝对路径
db_driver: "sqlite"
db_database: /tmp/mars-sqlite.db
# 如果是 'mysql' 以下均为必填项，如果是 'sqlite' 就不用填
db_host: 127.0.0.1
db_port: 3306
db_username: root
db_password: ""
db_slow_log_enabled: true
# "ns", "us" (or "µs"), "ms", "s", "m", "h"
db_slow_log_threshold: 200ms

tracing_endpoint: ""

# 集群外网访问 ip
external_ip: "127.0.0.1"

install_timeout: 90s

# imagepullsecrets: docker 私有镜像仓库需要配置相关的账号密码以及仓库地址
# server default: "https://index.docker.io/v1/"
imagepullsecrets:
  - username: "jack"
    password: "12345"
    email: "jack@example.com"
    # server: ""
  - username: "john"
    password: "12345"
    email: "john@example.com"
    server: "registry.cn-hangzhou.aliyuncs.com"

#oidc:
#  - name: "sso1"
#    enabled: true
#    provider_url: "http://127.0.0.1:9001"
#    client_id: "sso-xxx"
#    client_secret: "xxxx"
#    redirect_url: "http://127.0.0.1:3000/auth/callback"
#  - name: "sso2"
#    enabled: true
#    provider_url: "http://127.0.0.1:9001"
#    client_id: "sso-xxx"
#    client_secret: "xxxx"
#    redirect_url: "http://127.0.0.1:3000/auth/callback"

admin_password: "123456"
private_key: |-
  -----BEGIN RSA PRIVATE KEY-----
  MIICWwIBAAKBgQCdx5ZBeL3P3lH2fU/8yd4E1L880DjaKCnnnQkya+kOE7kkJNtP
  xW4WIKsBgXUPtXUYk/uA5AkklJ/1ssiTbkM/G5J54ThsACarhiNijUznD81c7g0Q
  6pbHYGAHU91wQgpcIv39cOKZVpFkEfIwgBMIKUvupBpGyXMU4YALVV23CQIDAQAB
  AoGARo+kzeDumlDlvONr6zRoOybd45eHZWEC5JchLtB9qJL/gH+PKQy1X+X6NDEu
  JflTxcsgdhMFV7u0EdCDzRNJtPKP/cU8hww0J2l3ZKTGzbbQnLIBFD3In8sEc9xe
  3ikEjqs0EgSh3uY5XEq8qzuX3cI+FNlGyOwzM+ZcN7nWfPUCQQDOURX82COQIfAT
  RjTshDQ55J/DUPPHyzpTER9OZNXYKp0IBBNzYyhJ6SHQHSuxHfL8W1FVHhmIsIBW
  GQWo0y7zAkEAw8ZPJ4QH5otMsIgIfwMuPX0rO+QxwmJ6eg9ADuFr5zv6HizjAVVP
  dKXuUU0gnemD4DncgiV2jZ0v2RzHK1aZEwJAR6G7gpgAcPB3jBmaEmwsPdV06rlW
  io2y6FhPiEZWQME62CeiITPSLyc0SC94lfwR+zAxYt4ae2zcgggaAO2hpQJAecA5
  d7S3iRu2XM6sofijaCAQpBV9EItX6dLUHqz4Av0cxmlZ33ljiYKr3CngD/SqS+cQ
  CGwt91H68MXh40TeuwJARxz1VMLq7hKo8J4scAW/YrBTE4N6malYjYoR2HFs+YwL
  cSE/4A4yfzTjN2r5GuJr8rTU7gU4Su9C8dLC0htWCA==
  -----END RSA PRIVATE KEY-----
