name: build_docker

on:
  push:
    tags:
      - "v*"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: paulhatch/semantic-version@v5.0.2
        id: get_version
        with:
          tag_prefix: "v"
      -
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build --platform linux/arm64,linux/amd64 \
             -t duccnzj/mars \
             -t duccnzj/mars:$tag \
             -t duccnzj/mars:v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} \
             -t registry.cn-hangzhou.aliyuncs.com/duc-cnzj/mars:$tag \
             -t registry.cn-hangzhou.aliyuncs.com/duc-cnzj/mars:v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} \
             -t registry.cn-hangzhou.aliyuncs.com/duc-cnzj/mars \
             --push .